---
- name: testing netapp mods
  hosts: 10.39.102.15
  gather_facts: false
  connection: local
  tasks:
    - name: Call Version
      include_role:
        name: ontap
        task_from: ontap_version.yml
