---
- name: testing netapp mods
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Get NetApp info as Cluster Admin (Password Authentication)
      netapp.ontap.na_ontap_info:
        hostname: "na-vsim"
        username: "admin"
        password: "admins_password"
        validate_certs: false
        use_rest: auto
      register: ontap_info
    - debug:
        msg: "{{ ontap_info.ontap_info }}"
